PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
export SHELL=/bin/bash
export LS_OPTIONS='--color=auto -l'
export PATH=${HOME}/bin:$PATH
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
cd

